# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
- maven
- master
- feature/*

pool:
  vmImage: ubuntu-latest

stages:
- stage: Setup
# steps:
  - template: components/ExtractAssemblyVersion.yml

# - stage: BuildAndTest
#   jobs:
#   - job: maven
# - template: components/maven.yml
#   jobs:
#   - job: python
# - template: components/python.yml
#   jobs:
#   - job: github-pr-comment
# - template: components/github-pr-comment.yml
