# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

# resources:
#   pipelines:
#   - pipeline: 4 # Name of the pipeline resource
#     source: rrron.ci_cd (1) # Name of the pipeline referenced by the pipeline resource
#     # project: CI_CD # Required only if the source pipeline is in another project
#     trigger: true

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
        print('variableInVariableGroup: $(variableInVariableGroup)')

- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      import os
      print (os.environ)

- script: echo This pipeline runs first !

- task: github-pr-comment@0
  inputs:
    userToken: '$(githubToken)'
    repository: '$(Build.Repository.Name)'
    prNumber: '$(System.PullRequest.PullRequestNumber)'
    bodyFilePath: ""
    extension: 'txt'
    getSubFolders: true

- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Pipeline.Workspace)'
    Contents: 'src'