# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
- maven
- master
- feature/*

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    StoreAsTar: true
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
        print('variableInVariableGroup: $(variableInVariableGroup)')

- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      import os
      print (os.environ)

- task: GitHubComment@0
  inputs:
    gitHubConnection: 'github.com_rrron'
    repositoryName: '$(Build.Repository.Name)'
    comment: '✅ Artifacts link: **[drop.tar](https://dev.azure.com/rstanevych0545/_apis/resources/Containers/2294508/drop?itemPath=drop%2Fdrop.tar)**'

