# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
- maven
- master
- feature/*

pool:
  vmImage: ubuntu-latest

variables:
  System.Debug: true
  
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
        print('variableInVariableGroup: $(variableInVariableGroup)')

- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      import os
      print (os.environ)

- task: github-pr-comment@0
  inputs:
    userToken: '$(githubToken)'
    repository: '$(Build.Repository.Name)'
    prNumber: '$(System.PullRequest.PullRequestNumber)'
    bodyFilePath: ""
    extension: 'txt'
    getSubFolders: true
    
- script: ls -la $(Pipeline.Workspace)/s/

- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Pipeline.Workspace)/s/'
    Contents: 'src'
    RemoveSourceFolder: true

- script: ls -la $(Pipeline.Workspace)/s/