# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
- maven
- master
- feature/*

pool:
  vmImage: ubuntu-latest

stages:
- stage: Setup
  jobs:
  - template: components/ExtractAssemblyVersion.yml

- stage: BuildAndTest
  jobs:
  - job: BuildAndTest
    steps:
    - template: components/maven.yml
  - job: python
    steps:
    - template: components/python.yml
  - job: github-pr-comment
    steps:
    - template: components/github-pr-comment.yml
