trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      import os
      print (os.environ)

- script: echo This pipeline runs first !